name: world_time_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Corrected dependencies
  http: ^1.3.0  # Keeping the latest http package
  flutter_dotenv: ^5.2.1  # Adding dotenv for environment variables
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/day.jpeg
    - assets/night.jpeg
    - assets/uk.png
    - assets/usa.png
    - assets/germany.png
    - assets/egypt.png
    - assets/kenya.png
    - assets/south_korea.png
    - assets/indonesia.png
    - assets/greece.png

